name: deploy to EC2

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: checkout code
              uses: actions/checkout@v3
            
            - name: validate html
              run: |
                sudo apt update
                sudo apt install tidy -y
                tidy -e index.html | tee output.txt
                if grep -q "Error" output.txt; then
                    echo "HTML validation failed"
                    exit 1
                fi

            - name: prepare build
              run: |
                mkdir builld
                rsync -av --exclude=build --exclude=.git --exclude=.github . build/
              
            - name: debug build
              run: |
                echo "===== BUILD STRUCTURE ====="
                ls -R build

            - name: deploy
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.HOST }}
                username: ubuntu
                key: ${{ secrets.SSH_KEY }}
                script: |
                  rm -rf /var/www/html/portfolio/*

            - name: copy files to EC2
              uses: appleboy/scp-action@v0.1.4
              with:
                host: ${{ secrets.HOST }}
                username: ubuntu
                key: ${{ secrets.SSH_KEY }}
                source: "build"
                target: /var/www/html/portfolio
                strip_components: 1


            - name: nginx reload
              uses: appleboy/ssh-action@v0.1.10
              with:
                host: ${{ secrets.HOST }}
                username: ubuntu
                key: ${{ secrets.SSH_KEY }}
                script: |
                  sudo nginx -t && sudo systemctl reload nginx